version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres-simplitec
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simplictec_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
